services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      GOLF_SITE_URL: ${GOLF_SITE_URL}
      COURSE_ID: ${COURSE_ID}
      TZ: ${TZ}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    restart: unless-stopped
    # Optional basic healthcheck (change path if you have a status endpoint)
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  dbdata: